// Capstone/ClientApp/src/Employees.tsx
import { Button } from "react-bootstrap";
import Layout from "./components/Layout";
import Table from "./components/DataTable";
import "./stylesheets/Employees.scss";
import { RowRecord, TableColumn } from "react-data-table-component";

interface Data {
  firstName: string;
  lastName: string;
  role: string;
  jobTitle: string;
  availability: string;
  maxHours: number;
}

const columns: TableColumn<RowRecord>[] = [
  {
    name: "First Name",
    selector: "firstName",
  },
  {
    name: "Last Name",
    selector: "lastName",
  },
  {
    name: "Role",
    selector: "role",
  },
  {
    name: "Job Title",
    selector: "jobTitle",
  },
  {
    name: "Availability",
    selector: "availability",
  },
  {
    name: "Max Hours",
    selector: "maxHours",
  },
];

const data = [
  {
    firstName: "Jack",
    lastName: "Dorsey",
    role: "FT",
    jobTitle: "dev",
    availability: "always",
    maxHours: 40,
    key: 1,
  },
];

const Employees = () => {
  return (
    <Layout>
      <>
        <div className="d-flex justify-content-between">
          <h1>Employees</h1>
          <Button href="/newEmployee">Create New</Button>
        </div>
        <Table columns={columns} data={data} />
      </>
    </Layout>
  );
};

export default Employees;

// packages/client/src/views/Employees.vue
<template>
  <div>
    <div className="flex justify-between">
      <h1>Employees</h1>
      <Button href="/employees/new">Create New</Button>
    </div>
    <DataTable
      :columns="columns"
      :data="persons"
      selection-mode="single"
      @selected="e => $router.push(`/employees/${e.id}`)"
    />
  </div>
</template>
<script setup lang="ts">
import usePerson from "@/store/modules/person/hook";
import { computed } from "@vue/reactivity";
import DataTable from "@/components/DataTable.vue";
import Button from "@/components/Button.vue";

const { GET_ALL } = usePerson();

const columns: InstanceType<typeof DataTable>["columns"] = [
  {
    title: "First Name",
    selector: "firstName"
  },
  {
    title: "Last Name",
    selector: "lastName"
  },
  {
    title: "Role",
    selector: "role"
  },
  {
    title: "Job Title",
    selector: "jobTitle"
  },
  {
    title: "Availability",
    selector: "availability"
  },
  {
    title: "Max Hours",
    selector: "maxWeeklyHours"
  }
];

const persons = computed<any>(GET_ALL);
</script>
<style scoped lang="postcss"></style>
